# Generated by Django 3.2.6 on 2021-08-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoModel',
            fields=[
                ('eventoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fechaEvento', models.DateField(blank=True, db_column='fecha_evento')),
                ('eventoTipo', models.IntegerField(choices=[(1, 'WORKSHOP'), (2, 'CONFERENCIA'), (3, 'SIMPOSIO')], db_column='tipo', verbose_name='Tipo del evento')),
                ('eventoLugar', models.IntegerField(choices=[(1, 'PERU'), (2, 'BRASIL'), (3, 'ARGENTINA'), (4, 'CHILE'), (5, 'MEXICO')], db_column='lugar', verbose_name='Tipo del evento')),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuarioId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('usuarioNombre', models.CharField(db_column='nombre', max_length=20, verbose_name='Nombre del usuario')),
                ('usuarioApellido', models.CharField(db_column='apellido', max_length=20, verbose_name='Apellido del usuario')),
                ('usuarioCorreo', models.EmailField(db_column='correo', max_length=254, unique=True, verbose_name='Correo del usuario')),
                ('usuarioTipo', models.IntegerField(choices=[(1, 'ADMINISTRADOR'), (2, 'USUARIO')], db_column='tipo', verbose_name='Tipo del usuario')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
